# -*- coding: utf-8 -*-
"""Model_5_LightGBM_Regressor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlY1TpW94qIA6-CbPAPwZ8Efa1JY5njb
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import lightgbm as lgb
import warnings
warnings.filterwarnings('ignore')

# ==========================================
# 1. โหลดข้อมูลและเตรียมชุดข้อมูล
# ==========================================
df = pd.read_csv("coffee_shop_sales.csv")

# ดึงเวลาเปิด-ปิด ของแต่ละสาขา
store_hours = df.groupby('store_location')['hour'].agg(['min', 'max']).to_dict(orient='index')

# จัดกลุ่มยอดขายรายวัน
daily_grouped = df.groupby(['transaction_date', 'store_location', 'name_day', 'month', 'hour', 'product_category'])['transaction_qty'].sum().reset_index(name='total_cups')

# ==========================================
# 2. การเข้ารหัสข้อมูล (Encoding)
# ==========================================
le_loc = LabelEncoder()
le_day = LabelEncoder()
le_cat = LabelEncoder()

daily_grouped['loc_encoded'] = le_loc.fit_transform(daily_grouped['store_location'])
daily_grouped['day_encoded'] = le_day.fit_transform(daily_grouped['name_day'])
daily_grouped['cat_encoded'] = le_cat.fit_transform(daily_grouped['product_category'])

# ==========================================
# 3. กำหนด Features และ Target แล้วเทรนโมเดล (LightGBM)
# ==========================================
X = daily_grouped[['loc_encoded', 'day_encoded', 'month', 'hour', 'cat_encoded']]
y = daily_grouped['total_cups']

# แบ่งข้อมูลสำหรับ Train 80% และ Test 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("⚡ กำลังสอน AI ด้วยอัลกอริทึม LightGBM Regressor...")

# สร้างโมเดล LightGBM
lgb_model = lgb.LGBMRegressor(
    n_estimators=300,        # จำนวนต้นไม้
    learning_rate=0.05,      # ความเร็วในการเรียนรู้
    max_depth=8,             # ความลึกของต้นไม้ (LightGBM มักจะใช้ค่านี้เพื่อคุมไม่ให้ Overfit)
    random_state=42,
    verbose=-1               # ปิดการแสดงข้อความ log รกๆ
)

# ระบุชื่อคอลัมน์ที่เป็น "หมวดหมู่ (Categorical)" ให้ LightGBM ทราบ
categorical_cols = ['loc_encoded', 'day_encoded', 'cat_encoded']

# เทรนรอบแรกเพื่อประเมินความแม่นยำ
lgb_model.fit(X_train, y_train, categorical_feature=categorical_cols)
preds = lgb_model.predict(X_test)

# --- คำนวณค่าความแม่นยำ ---
mae = mean_absolute_error(y_test, preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))
r2 = r2_score(y_test, preds)

# เทรนทับอีกรอบด้วยข้อมูล "ทั้งหมด 100%"
lgb_model.fit(X, y, categorical_feature=categorical_cols)
print("✅ สอนเสร็จสมบูรณ์!\n")

# ==========================================
# 4. ฟังก์ชันพยากรณ์อัจฉริยะ (Interactive Predictor)
# ==========================================
def lightgbm_demand_predictor():
    print("="*85)
    print(" ⚡ ระบบทำนายยอดขายอัจฉริยะ (LightGBM Regression) ⚡ ")
    print("="*85)

    print("\n📊 ประสิทธิภาพและความน่าเชื่อถือของ AI (Model Evaluation):")
    print(f" 1. MAE (ความคลาดเคลื่อนเฉลี่ย) : ±{mae:.2f} ชิ้น")
    print(f" 2. RMSE (จุดบอดสูงสุดโดยเฉลี่ย) : ±{rmse:.2f} ชิ้น")
    print(f" 3. R-Squared (ความแม่นยำของแพทเทิร์น) : {r2 * 100:.1f}%")
    print("-" * 85)

    # รับค่าข้อมูลจากผู้ใช้
    locations = list(le_loc.classes_)
    print(f"\n📍 สาขาที่มีในระบบ: {', '.join(locations)}")
    user_loc = input("พิมพ์ชื่อสาขา (เช่น Hell's Kitchen): ").strip()

    if user_loc not in locations:
        print("❌ ชื่อสาขาไม่ถูกต้อง กรุณารันใหม่อีกครั้ง")
        return

    min_h, max_h = store_hours[user_loc]['min'], store_hours[user_loc]['max']
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    print(f"\n📅 วัน: {', '.join(days)}")
    user_day = input("พิมพ์ชื่อวันภาษาอังกฤษ: ").strip()

    try:
        user_month = int(input("📅 พิมพ์เลขเดือน (1-12): ").strip())
        print(f"\n⏰ เวลาเปิดทำการของสาขา {user_loc} คือตั้งแต่ {min_h}:00 น. ถึง {max_h}:00 น.")
        user_hour = int(input(f"พิมพ์เวลาชั่วโมง ({min_h}-{max_h}): ").strip())

        if user_day not in days or not (1 <= user_month <= 12):
            print("❌ ข้อมูลวันหรือเดือนไม่ถูกต้อง")
            return
        if not (min_h <= user_hour <= max_h):
            print(f"❌ สาขา {user_loc} ไม่ได้เปิดทำการในเวลา {user_hour}:00 น.!")
            return
    except ValueError:
        print("❌ ข้อมูลเวลาและเดือนต้องเป็นตัวเลขเท่านั้น")
        return

    print("\n" + "="*85)

    # --- กระบวนการทำนาย ---
    loc_enc = le_loc.transform([user_loc])[0]
    day_enc = le_day.transform([user_day])[0]
    all_categories = le_cat.classes_
    all_cat_encoded = le_cat.transform(all_categories)

    predict_data = pd.DataFrame({
        'loc_encoded': [loc_enc] * len(all_categories),
        'day_encoded': [day_enc] * len(all_categories),
        'month': [user_month] * len(all_categories),
        'hour': [user_hour] * len(all_categories),
        'cat_encoded': all_cat_encoded
    })

    # พยากรณ์ด้วย LightGBM
    predicted_qty = lgb_model.predict(predict_data)

    results_df = pd.DataFrame({
        'หมวดหมู่สินค้า': all_categories,
        'ยอดขายที่คาดหมาย (ชิ้น)': predicted_qty
    })

    results_df = results_df[results_df['ยอดขายที่คาดหมาย (ชิ้น)'] > 0]
    results_df = results_df.sort_values(by='ยอดขายที่คาดหมาย (ชิ้น)', ascending=False)

    best_cat = results_df.iloc[0]['หมวดหมู่สินค้า'] if not results_df.empty else "ไม่มีข้อมูลคาดการณ์"

    # --- แสดงผลสรุป ---
    print(f"🎯 สรุปผลการทำนายด้วย LightGBM Regressor")
    print(f" 📍 สาขา  : {user_loc}")
    print(f" 📅 วันที่  : {user_day} (เดือนที่ {user_month})")
    print(f" ⏰ เวลา   : {user_hour}:00 น.")
    print("-" * 85)
    print(f"🌟 เมนูยอดฮิตอันดับ 1 น่าจะเป็น: >> {best_cat} <<")
    print("-" * 85)

    print("💡 การจัดอันดับคาดการณ์จาก AI (Top 6 Predictions):")
    total_predicted = results_df['ยอดขายที่คาดหมาย (ชิ้น)'].sum()

    if total_predicted > 0:
        rank_ai = 1
        for _, row in results_df.head(6).iterrows():
            percent = (row['ยอดขายที่คาดหมาย (ชิ้น)'] / total_predicted) * 100
            print(f"   {rank_ai}. {row['หมวดหมู่สินค้า']:<20} : คาดว่าจะขายได้ประมาณ {row['ยอดขายที่คาดหมาย (ชิ้น)']:.1f} ชิ้น ({percent:.1f}%)")
            rank_ai += 1
    else:
        print("   (AI คาดการณ์ว่าอาจจะไม่มีการขายในช่วงเวลานี้ หรือขายน้อยมาก)")

    print("\n📈 ข้อมูลสถิติของจริงย้อนหลัง (นำมาเทียบเพื่อความมั่นใจ):")
    sample_history = daily_grouped[(daily_grouped['store_location'] == user_loc) &
                                   (daily_grouped['name_day'] == user_day) &
                                   (daily_grouped['hour'] == user_hour) &
                                   (daily_grouped['month'] == user_month)]

    if not sample_history.empty:
        monthly_sum = sample_history.groupby('product_category')['total_cups'].sum().reset_index()
        monthly_sum = monthly_sum.sort_values(by='total_cups', ascending=False)
        total_cups_period = monthly_sum['total_cups'].sum()

        print(f"   (ยอดขายรวมทั้งหมดในอดีต ณ ช่วงเวลานี้คือ {total_cups_period} ชิ้น/แก้ว)")
        rank_hist = 1
        for _, row in monthly_sum.head(6).iterrows():
            sales_percent = (row['total_cups'] / total_cups_period) * 100
            print(f"   {rank_hist}. {row['product_category']:<20} : เคยขายได้ {row['total_cups']:<4} ชิ้น ({sales_percent:.1f}%)")
            rank_hist += 1
    else:
        print("   - (ไม่พบข้อมูลการขายในอดีตสำหรับเงื่อนไขนี้)")

    print("="*85)

# 4. เรียกใช้งาน
lightgbm_demand_predictor()