# -*- coding: utf-8 -*-
"""Model_1_Random_Forest_Classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Co19-fY8cMxzFReYlhUC6YpWJeHtJst2
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import warnings
warnings.filterwarnings('ignore')

# --- 1. โหลดข้อมูลและเตรียมชุดข้อมูล ---
df = pd.read_csv("coffee_shop_sales.csv")
store_hours = df.groupby('store_location')['hour'].agg(['min', 'max']).to_dict(orient='index')
daily_grouped = df.groupby(['transaction_date', 'store_location', 'name_day', 'month', 'hour', 'product_category'])['transaction_qty'].sum().reset_index(name='total_cups')

# หาหมวดหมู่ที่ขายดีที่สุดเป็น Target สำหรับ Classification
idx = daily_grouped.groupby(['transaction_date', 'store_location', 'hour'])['total_cups'].idxmax()
daily_best_sellers = daily_grouped.loc[idx].reset_index(drop=True)

le_loc, le_day, le_cat = LabelEncoder(), LabelEncoder(), LabelEncoder()
daily_best_sellers['loc_encoded'] = le_loc.fit_transform(daily_best_sellers['store_location'])
daily_best_sellers['day_encoded'] = le_day.fit_transform(daily_best_sellers['name_day'])
daily_best_sellers['cat_encoded'] = le_cat.fit_transform(daily_best_sellers['product_category'])

X = daily_best_sellers[['loc_encoded', 'day_encoded', 'hour', 'month']]
y = daily_best_sellers['cat_encoded']

# --- 2. ส่วนเพิ่มเติม: ประเมินโมเดลเพื่อหาค่า 4 Metrics ---
# แบ่งข้อมูลไว้สอบ 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# เทรนโมเดลชั่วคราวเพื่อทำข้อสอบ
rf_eval = RandomForestClassifier(n_estimators=150, max_depth=10, random_state=42)
rf_eval.fit(X_train, y_train)
preds = rf_eval.predict(X_test)

# คำนวณค่าทั้ง 4 (ใช้ average='weighted' เพราะเป็นแบบทายหลายหมวดหมู่)
acc = accuracy_score(y_test, preds)
prec = precision_score(y_test, preds, average='weighted', zero_division=0)
rec = recall_score(y_test, preds, average='weighted', zero_division=0)
f1 = f1_score(y_test, preds, average='weighted', zero_division=0)

# --- 3. เทรนโมเดลจริงสำหรับใช้งาน ---
# เทรนด้วยข้อมูลทั้งหมด 100% เพื่อให้โมเดลเก่งที่สุด
rf_model = RandomForestClassifier(n_estimators=150, max_depth=10, random_state=42)
rf_model.fit(X, y)

# ==========================================
# 4. ฟังก์ชันพยากรณ์ (พร้อมแสดงค่าประเมินผล 4 ค่า)
# ==========================================
def top5_demand_predictor_v2():
    print("="*75)
    print(" ☕ ระบบทำนายยอดขายอัจฉริยะ (Random Forest Classifier) ☕ ")
    print("="*75)

    # แสดงประสิทธิภาพ 4 ค่า ที่คำนวณมาได้
    print("\n📊 ประสิทธิภาพความน่าเชื่อถือของ AI (Model Evaluation):")
    print(f" - Accuracy  (ความแม่นยำรวม) : {acc * 100:.2f}%")
    print(f" - Precision (ความแม่นยำเมื่อฟันธง) : {prec * 100:.2f}%")
    print(f" - Recall    (ความครอบคลุม) : {rec * 100:.2f}%")
    print(f" - F1-Score  (ความสมดุลของโมเดล) : {f1 * 100:.2f}%")
    print("-" * 75)

    locations = list(le_loc.classes_)
    print(f"\n📍 สาขาที่มีในระบบ: {', '.join(locations)}")
    user_loc = input("พิมพ์ชื่อสาขา (เช่น Hell's Kitchen): ").strip()

    if user_loc not in locations:
        print("❌ ชื่อสาขาไม่ถูกต้อง กรุณารันใหม่อีกครั้ง")
        return

    min_h, max_h = store_hours[user_loc]['min'], store_hours[user_loc]['max']
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    print(f"\n📅 วัน: {', '.join(days)}")
    user_day = input("พิมพ์ชื่อวันภาษาอังกฤษ: ").strip()

    try:
        user_month = int(input("📅 พิมพ์เลขเดือน (1-12): ").strip())
        print(f"\n⏰ เวลาเปิดทำการของสาขา {user_loc} คือตั้งแต่ {min_h}:00 น. ถึง {max_h}:00 น.")
        user_hour = int(input(f"พิมพ์เวลาชั่วโมง ({min_h}-{max_h}): ").strip())

        if user_day not in days or not (1 <= user_month <= 12):
            print("❌ ข้อมูลวันหรือเดือนไม่ถูกต้อง")
            return
        if not (min_h <= user_hour <= max_h):
            print(f"❌ สาขา {user_loc} ไม่ได้เปิดทำการในเวลา {user_hour}:00 น.!")
            return
    except ValueError:
        print("❌ ข้อมูลเวลาและเดือนต้องเป็นตัวเลขเท่านั้น")
        return

    print("\n" + "="*75)

    loc_enc = le_loc.transform([user_loc])[0]
    day_enc = le_day.transform([user_day])[0]

    probs = rf_model.predict_proba([[loc_enc, day_enc, user_hour, user_month]])[0]
    prob_df = pd.DataFrame({'หมวดหมู่สินค้า': le_cat.classes_, 'ความน่าจะเป็น': probs * 100}).sort_values(by='ความน่าจะเป็น', ascending=False)
    best_cat = prob_df.iloc[0]['หมวดหมู่สินค้า']

    print(f"🎯 สรุปผลการทำนาย")
    print(f" 📍 สาขา  : {user_loc}")
    print(f" 📅 วันที่  : {user_day} (เดือนที่ {user_month})")
    print(f" ⏰ เวลา   : {user_hour}:00 น.")
    print("-" * 75)
    print(f"🌟 เมนูที่จะเป็นที่ 1 ประจำวันน่าจะเป็น: >> {best_cat} <<")
    print("-" * 75)

    print("💡 การจัดอันดับจากโมเดล AI (คาดการณ์โอกาสที่จะเป็นที่ 1):")
    rank_ai = 1
    for _, row in prob_df.head(6).iterrows():
        print(f"   {rank_ai}. {row['หมวดหมู่สินค้า']:<20} : โอกาส {row['ความน่าจะเป็น']:.1f}%")
        rank_ai += 1

    print("\n📈 ข้อมูลสถิติของจริงย้อนหลัง (เปรียบเทียบสัดส่วนยอดขายรวม):")

    sample_history = daily_grouped[(daily_grouped['store_location'] == user_loc) &
                                   (daily_grouped['name_day'] == user_day) &
                                   (daily_grouped['hour'] == user_hour) &
                                   (daily_grouped['month'] == user_month)]

    if not sample_history.empty:
        monthly_sum = sample_history.groupby('product_category')['total_cups'].sum().reset_index()
        monthly_sum = monthly_sum.sort_values(by='total_cups', ascending=False)

        total_cups_period = monthly_sum['total_cups'].sum()
        print(f"   (จำนวนสินค้าที่ขายได้ทั้งหมดในช่วงเวลานี้คือ {total_cups_period} ชิ้น/แก้ว)")

        rank_hist = 1
        for _, row in monthly_sum.head(6).iterrows():
            sales_percent = (row['total_cups'] / total_cups_period) * 100
            print(f"   {rank_hist}. {row['product_category']:<20} : ขายได้ {row['total_cups']:<4} ชิ้น (คิดเป็น {sales_percent:.1f}% ของยอดทั้งหมด)")
            rank_hist += 1
    else:
        print("   - (ไม่พบข้อมูลการขายในอดีตสำหรับเงื่อนไขนี้)")

    print("="*75)

# เรียกใช้งานระบบ
top5_demand_predictor_v2()