# -*- coding: utf-8 -*-
"""Model_3_XGBoost_Regressor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYuf9BlwyvR4VDSeD3Mw6VuKvHgX30M5
"""

import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, r2_score
import warnings
warnings.filterwarnings('ignore')

# ==========================================
# 1. โหลดข้อมูลและเตรียมชุดข้อมูล (Data Prep for Regression)
# ==========================================
df = pd.read_csv("coffee_shop_sales.csv")

# ดึงเวลาเปิด-ปิด ของแต่ละสาขาอัตโนมัติเพื่อป้องกันผู้ใช้กรอกเวลาผิด
store_hours = df.groupby('store_location')['hour'].agg(['min', 'max']).to_dict(orient='index')

# จัดกลุ่มยอดขายรายวัน โดยเก็บ 'ทุกหมวดหมู่สินค้า' และ 'จำนวนแก้ว/ชิ้นที่ขายได้' (total_cups) เป็นเป้าหมายหลัก
daily_grouped = df.groupby(['transaction_date', 'store_location', 'name_day', 'month', 'hour', 'product_category'])['transaction_qty'].sum().reset_index(name='total_cups')

# ==========================================
# 2. การเข้ารหัสข้อมูล (Encoding)
# ==========================================
le_loc = LabelEncoder()
le_day = LabelEncoder()
le_cat = LabelEncoder()

# แปลงตัวแปรข้อความ (Features) ให้เป็นตัวเลขเพื่อให้ AI อ่านเข้าใจ
daily_grouped['loc_encoded'] = le_loc.fit_transform(daily_grouped['store_location'])
daily_grouped['day_encoded'] = le_day.fit_transform(daily_grouped['name_day'])
daily_grouped['cat_encoded'] = le_cat.fit_transform(daily_grouped['product_category'])

# ==========================================
# 3. กำหนด Features และ Target แล้วเทรนโมเดล (XGBoost)
# ==========================================
X = daily_grouped[['loc_encoded', 'day_encoded', 'month', 'hour', 'cat_encoded']]
y = daily_grouped['total_cups']

# แบ่งข้อมูลสำหรับ Train 80% และ Test 20% (เพื่อนำมาประเมินค่า MAE และ R-Squared)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("🤖 กำลังสอน AI ด้วยอัลกอริทึม XGBoost...")
xgb_model = xgb.XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=6,
    random_state=42,
    objective='reg:squarederror'
)

# เทรนรอบแรกเพื่อประเมินความแม่นยำ
xgb_model.fit(X_train, y_train)

# คำนวณค่าความแม่นยำของ AI (MAE และ R-Squared)
preds = xgb_model.predict(X_test)
mae = mean_absolute_error(y_test, preds)
r2 = r2_score(y_test, preds)

# เทรนทับอีกรอบด้วยข้อมูล "ทั้งหมด 100%" เพื่อให้โมเดลเก่งที่สุดก่อนนำไปใช้งานจริง (Production)
xgb_model.fit(X, y)
print("✅ สอนเสร็จสมบูรณ์!\n")

# ==========================================
# 4. ฟังก์ชันพยากรณ์และจัดอันดับด้วย (Interactive Predictor)
# ==========================================
def xgboost_demand_predictor():
    print("="*85)
    print(" 🚀 ระบบทำนายยอดขายอัจฉริยะ (XGBoost Regression - Predict Quantity) 🚀 ")
    print("="*85)

    # แสดงค่าประเมินความน่าเชื่อถือของ Regression
    print("\n📊 ประสิทธิภาพและความน่าเชื่อถือของ AI (Model Evaluation):")
    print(f" - ค่าความคลาดเคลื่อนเฉลี่ย (MAE) : ±{mae:.2f} ชิ้น/แก้ว")
    print(f"   (หมายความว่า AI มักจะทายตัวเลขคลาดเคลื่อนจากความเป็นจริงเพียงแค่ {mae:.2f} ชิ้นเท่านั้น)")
    print(f" - ความแม่นยำในการจับแพทเทิร์น (R-Squared) : {r2 * 100:.1f}%")
    print("-" * 85)

    # รับค่าสาขา
    locations = list(le_loc.classes_)
    print(f"\n📍 สาขาที่มีในระบบ: {', '.join(locations)}")
    user_loc = input("พิมพ์ชื่อสาขา (เช่น Hell's Kitchen): ").strip()

    if user_loc not in locations:
        print("❌ ชื่อสาขาไม่ถูกต้อง กรุณารันใหม่อีกครั้ง")
        return

    # ตรวจสอบเวลาเปิด-ปิด
    min_h, max_h = store_hours[user_loc]['min'], store_hours[user_loc]['max']

    # รับค่าวัน
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    print(f"\n📅 วัน: {', '.join(days)}")
    user_day = input("พิมพ์ชื่อวันภาษาอังกฤษ: ").strip()

    # รับค่าเดือนและเวลา พร้อมตรวจสอบเงื่อนไข
    try:
        user_month = int(input("📅 พิมพ์เลขเดือน (1-12): ").strip())
        print(f"\n⏰ เวลาเปิดทำการของสาขา {user_loc} คือตั้งแต่ {min_h}:00 น. ถึง {max_h}:00 น.")
        user_hour = int(input(f"พิมพ์เวลาชั่วโมง ({min_h}-{max_h}): ").strip())

        if user_day not in days or not (1 <= user_month <= 12):
            print("❌ ข้อมูลวันหรือเดือนไม่ถูกต้อง")
            return
        if not (min_h <= user_hour <= max_h):
            print(f"❌ สาขา {user_loc} ไม่ได้เปิดทำการในเวลา {user_hour}:00 น.!")
            return
    except ValueError:
        print("❌ ข้อมูลเวลาและเดือนต้องเป็นตัวเลขเท่านั้น")
        return

    print("\n" + "="*85)

    # --- กระบวนการทำนายของ XGBoost ---
    loc_enc = le_loc.transform([user_loc])[0]
    day_enc = le_day.transform([user_day])[0]
    all_categories = le_cat.classes_
    all_cat_encoded = le_cat.transform(all_categories)

    # ให้โมเดลประเมินยอดขายของ 'ทุกหมวดหมู่' พร้อมๆ กัน
    predict_data = pd.DataFrame({
        'loc_encoded': [loc_enc] * len(all_categories),
        'day_encoded': [day_enc] * len(all_categories),
        'month': [user_month] * len(all_categories),
        'hour': [user_hour] * len(all_categories),
        'cat_encoded': all_cat_encoded
    })

    predicted_qty = xgb_model.predict(predict_data)

    # จัดเรียงผลลัพธ์
    results_df = pd.DataFrame({
        'หมวดหมู่สินค้า': all_categories,
        'ยอดขายที่คาดหมาย (ชิ้น)': predicted_qty
    })

    results_df = results_df[results_df['ยอดขายที่คาดหมาย (ชิ้น)'] > 0]
    results_df = results_df.sort_values(by='ยอดขายที่คาดหมาย (ชิ้น)', ascending=False)

    best_cat = results_df.iloc[0]['หมวดหมู่สินค้า'] if not results_df.empty else "ไม่มีข้อมูลคาดการณ์"

    # แสดงผลสรุป
    print(f"🎯 สรุปผลการทำนายด้วย XGBoost Regressor")
    print(f" 📍 สาขา  : {user_loc}")
    print(f" 📅 วันที่  : {user_day} (เดือนที่ {user_month})")
    print(f" ⏰ เวลา   : {user_hour}:00 น.")
    print("-" * 85)
    print(f"🌟 เมนูยอดฮิตอันดับ 1 น่าจะเป็น: >> {best_cat} <<")
    print("-" * 85)

    print("💡 การจัดอันดับคาดการณ์จาก AI (Top 6 Predictions):")
    total_predicted = results_df['ยอดขายที่คาดหมาย (ชิ้น)'].sum()

    if total_predicted > 0:
        rank_ai = 1
        for _, row in results_df.head(6).iterrows():
            percent = (row['ยอดขายที่คาดหมาย (ชิ้น)'] / total_predicted) * 100
            print(f"   {rank_ai}. {row['หมวดหมู่สินค้า']:<20} : คาดว่าจะขายได้ประมาณ {row['ยอดขายที่คาดหมาย (ชิ้น)']:.1f} ชิ้น ({percent:.1f}%)")
            rank_ai += 1
    else:
        print("   (AI คาดการณ์ว่าอาจจะไม่มีการขายในช่วงเวลานี้ หรือขายน้อยมาก)")

    print("\n📈 ข้อมูลสถิติของจริงย้อนหลัง (นำมาเทียบเพื่อความมั่นใจ):")
    sample_history = daily_grouped[(daily_grouped['store_location'] == user_loc) &
                                   (daily_grouped['name_day'] == user_day) &
                                   (daily_grouped['hour'] == user_hour) &
                                   (daily_grouped['month'] == user_month)]

    if not sample_history.empty:
        monthly_sum = sample_history.groupby('product_category')['total_cups'].sum().reset_index()
        monthly_sum = monthly_sum.sort_values(by='total_cups', ascending=False)
        total_cups_period = monthly_sum['total_cups'].sum()

        print(f"   (ยอดขายรวมทั้งหมดในอดีต ณ ช่วงเวลานี้คือ {total_cups_period} ชิ้น/แก้ว)")
        rank_hist = 1
        for _, row in monthly_sum.head(6).iterrows():
            sales_percent = (row['total_cups'] / total_cups_period) * 100
            print(f"   {rank_hist}. {row['product_category']:<20} : เคยขายได้ {row['total_cups']:<4} ชิ้น ({sales_percent:.1f}%)")
            rank_hist += 1
    else:
        print("   - (ไม่พบข้อมูลการขายในอดีตสำหรับเงื่อนไขนี้)")

    print("="*85)

# 5. เรียกใช้งานระบบ
xgboost_demand_predictor()

