# -*- coding: utf-8 -*-
"""Model_6_ANN_Regressor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I40nZDpOKdhwj2h6uX6UBBGAUfUESO7v
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

# ==========================================
# 1. โหลดข้อมูลและเตรียมชุดข้อมูล
# ==========================================
df = pd.read_csv("coffee_shop_sales.csv")

# ดึงเวลาเปิด-ปิด ของแต่ละสาขา
store_hours = df.groupby('store_location')['hour'].agg(['min', 'max']).to_dict(orient='index')

# จัดกลุ่มยอดขายรายวัน
daily_grouped = df.groupby(['transaction_date', 'store_location', 'name_day', 'month', 'hour', 'product_category'])['transaction_qty'].sum().reset_index(name='total_cups')

# ==========================================
# 2. การเข้ารหัสข้อมูล (Encoding)
# ==========================================
le_loc = LabelEncoder()
le_day = LabelEncoder()
le_cat = LabelEncoder()

daily_grouped['loc_encoded'] = le_loc.fit_transform(daily_grouped['store_location'])
daily_grouped['day_encoded'] = le_day.fit_transform(daily_grouped['name_day'])
daily_grouped['cat_encoded'] = le_cat.fit_transform(daily_grouped['product_category'])

# ==========================================
# 3. กำหนด Features / Target และทำ Data Scaling (สำคัญมากสำหรับ ANN!)
# ==========================================
X = daily_grouped[['loc_encoded', 'day_encoded', 'month', 'hour', 'cat_encoded']]
y = daily_grouped['total_cups']

# แบ่งข้อมูลสำหรับ Train 80% และ Test 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# --- กระบวนการปรับสเกลตัวเลข (Data Scaling) ---
scaler = StandardScaler()
# ให้ Scaler เรียนรู้จาก X_train และปรับสเกลทันที
X_train_scaled = scaler.fit_transform(X_train)
# นำไม้บรรทัดเดิมไปปรับสเกล X_test (ห้ามใช้ fit กับชุด test เด็ดขาด)
X_test_scaled = scaler.transform(X_test)

print("🧠 กำลังสอนโครงข่ายประสาทเทียม (ANN / MLP Regressor)...")
# สร้างโมเดล โครงข่ายประสาทเทียม
ann_model = MLPRegressor(
    hidden_layer_sizes=(64, 64), # สร้างสมองชั้นซ่อนเร้น 2 ชั้น ชั้นละ 64 เซลล์ประสาท (Neurons)
    activation='relu',           # ฟังก์ชันกระตุ้นเซลล์ประสาทยอดนิยม
    solver='adam',               # อัลกอริทึมการเรียนรู้
    max_iter=500,                # จำนวนรอบที่ให้โมเดลอ่านหนังสือซ้ำ (Epochs)
    random_state=42,
    early_stopping=True          # หยุดเรียนรู้ถ้ารู้สึกว่าเริ่มจำข้อสอบ (ป้องกัน Overfit)
)

# เทรนรอบแรกเพื่อประเมินความแม่นยำ (ต้องใช้ข้อมูลที่ Scaled แล้วเท่านั้น)
ann_model.fit(X_train_scaled, y_train)
preds = ann_model.predict(X_test_scaled)

# --- คำนวณค่าความแม่นยำ ---
mae = mean_absolute_error(y_test, preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))
r2 = r2_score(y_test, preds)

# ปรับสเกลข้อมูล "ทั้งหมด 100%" ก่อนเทรนใช้งานจริง
X_scaled_all = scaler.fit_transform(X)
ann_model.fit(X_scaled_all, y)
print("✅ สอนเสร็จสมบูรณ์!\n")

# ==========================================
# 4. ฟังก์ชันพยากรณ์อัจฉริยะ (Interactive Predictor)
# ==========================================
def ann_demand_predictor():
    print("="*85)
    print(" 🧠 ระบบทำนายยอดขายด้วยโครงข่ายประสาทเทียม (ANN Regression) 🧠 ")
    print("="*85)

    print("\n📊 ประสิทธิภาพและความน่าเชื่อถือของ AI (Model Evaluation):")
    print(f" 1. MAE (ความคลาดเคลื่อนเฉลี่ย) : ±{mae:.2f} ชิ้น")
    print(f" 2. RMSE (จุดบอดสูงสุดโดยเฉลี่ย) : ±{rmse:.2f} ชิ้น")
    print(f" 3. R-Squared (ความแม่นยำของแพทเทิร์น) : {r2 * 100:.1f}%")
    print("-" * 85)

    locations = list(le_loc.classes_)
    print(f"\n📍 สาขาที่มีในระบบ: {', '.join(locations)}")
    user_loc = input("พิมพ์ชื่อสาขา (เช่น Hell's Kitchen): ").strip()

    if user_loc not in locations:
        print("❌ ชื่อสาขาไม่ถูกต้อง กรุณารันใหม่อีกครั้ง")
        return

    min_h, max_h = store_hours[user_loc]['min'], store_hours[user_loc]['max']
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    print(f"\n📅 วัน: {', '.join(days)}")
    user_day = input("พิมพ์ชื่อวันภาษาอังกฤษ: ").strip()

    try:
        user_month = int(input("📅 พิมพ์เลขเดือน (1-12): ").strip())
        print(f"\n⏰ เวลาเปิดทำการของสาขา {user_loc} คือตั้งแต่ {min_h}:00 น. ถึง {max_h}:00 น.")
        user_hour = int(input(f"พิมพ์เวลาชั่วโมง ({min_h}-{max_h}): ").strip())

        if user_day not in days or not (1 <= user_month <= 12):
            print("❌ ข้อมูลวันหรือเดือนไม่ถูกต้อง")
            return
        if not (min_h <= user_hour <= max_h):
            print(f"❌ สาขา {user_loc} ไม่ได้เปิดทำการในเวลา {user_hour}:00 น.!")
            return
    except ValueError:
        print("❌ ข้อมูลเวลาและเดือนต้องเป็นตัวเลขเท่านั้น")
        return

    print("\n" + "="*85)

    # --- กระบวนการทำนาย ---
    loc_enc = le_loc.transform([user_loc])[0]
    day_enc = le_day.transform([user_day])[0]
    all_categories = le_cat.classes_
    all_cat_encoded = le_cat.transform(all_categories)

    predict_data = pd.DataFrame({
        'loc_encoded': [loc_enc] * len(all_categories),
        'day_encoded': [day_enc] * len(all_categories),
        'month': [user_month] * len(all_categories),
        'hour': [user_hour] * len(all_categories),
        'cat_encoded': all_cat_encoded
    })

    # **ข้อควรระวังสุดๆ:** ก่อนให้ ANN ทำนาย ต้องทำการ Scale ข้อมูลชุดคำถามด้วย!
    predict_data_scaled = scaler.transform(predict_data)

    predicted_qty = ann_model.predict(predict_data_scaled)

    results_df = pd.DataFrame({
        'หมวดหมู่สินค้า': all_categories,
        'ยอดขายที่คาดหมาย (ชิ้น)': predicted_qty
    })

    results_df = results_df[results_df['ยอดขายที่คาดหมาย (ชิ้น)'] > 0]
    results_df = results_df.sort_values(by='ยอดขายที่คาดหมาย (ชิ้น)', ascending=False)

    best_cat = results_df.iloc[0]['หมวดหมู่สินค้า'] if not results_df.empty else "ไม่มีข้อมูลคาดการณ์"

    # --- แสดงผลสรุป ---
    print(f"🎯 สรุปผลการทำนายด้วย ANN Regressor")
    print(f" 📍 สาขา  : {user_loc}")
    print(f" 📅 วันที่  : {user_day} (เดือนที่ {user_month})")
    print(f" ⏰ เวลา   : {user_hour}:00 น.")
    print("-" * 85)
    print(f"🌟 เมนูยอดฮิตอันดับ 1 น่าจะเป็น: >> {best_cat} <<")
    print("-" * 85)

    print("💡 การจัดอันดับคาดการณ์จาก AI (Top 5 Predictions):")
    total_predicted = results_df['ยอดขายที่คาดหมาย (ชิ้น)'].sum()

    if total_predicted > 0:
        rank_ai = 1
        for _, row in results_df.head(5).iterrows():
            percent = (row['ยอดขายที่คาดหมาย (ชิ้น)'] / total_predicted) * 100
            print(f"   {rank_ai}. {row['หมวดหมู่สินค้า']:<20} : คาดว่าจะขายได้ประมาณ {row['ยอดขายที่คาดหมาย (ชิ้น)']:.1f} ชิ้น ({percent:.1f}%)")
            rank_ai += 1
    else:
        print("   (AI คาดการณ์ว่าอาจจะไม่มีการขายในช่วงเวลานี้ หรือขายน้อยมาก)")

    print("\n📈 ข้อมูลสถิติของจริงย้อนหลัง (นำมาเทียบเพื่อความมั่นใจ):")
    sample_history = daily_grouped[(daily_grouped['store_location'] == user_loc) &
                                   (daily_grouped['name_day'] == user_day) &
                                   (daily_grouped['hour'] == user_hour) &
                                   (daily_grouped['month'] == user_month)]

    if not sample_history.empty:
        monthly_sum = sample_history.groupby('product_category')['total_cups'].sum().reset_index()
        monthly_sum = monthly_sum.sort_values(by='total_cups', ascending=False)
        total_cups_period = monthly_sum['total_cups'].sum()

        print(f"   (ยอดขายรวมทั้งหมดในอดีต ณ ช่วงเวลานี้คือ {total_cups_period} ชิ้น/แก้ว)")
        rank_hist = 1
        for _, row in monthly_sum.head(5).iterrows():
            sales_percent = (row['total_cups'] / total_cups_period) * 100
            print(f"   {rank_hist}. {row['product_category']:<20} : เคยขายได้ {row['total_cups']:<4} ชิ้น ({sales_percent:.1f}%)")
            rank_hist += 1
    else:
        print("   - (ไม่พบข้อมูลการขายในอดีตสำหรับเงื่อนไขนี้)")

    print("="*85)

# 5. เรียกใช้งาน
ann_demand_predictor()